<a href="https://colab.research.google.com/github/rizkaaa19/MachineLearning/blob/main/UAS/Reproduce%20Code/Reproduce_Codes_00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **UAS Machine Learning**

Nama : Rizka Rahmadina

NIM : 1103204115

Reproduce Codes "00_pytorch_fundamentals"

### Create a random tensor with shape (10, 5).

In [1]:
# Import torch
import torch

# Create random tensor with shape (10, 5)
Z = torch.rand(size=(10, 5))

# Print the random tensor and its shape
print(Z)
print(Z.shape)


tensor([[0.4026, 0.0344, 0.7101, 0.2210, 0.7952],
        [0.9549, 0.3402, 0.3371, 0.4666, 0.3622],
        [0.4782, 0.2338, 0.7395, 0.6043, 0.2588],
        [0.4999, 0.1287, 0.8665, 0.9595, 0.1299],
        [0.0966, 0.0054, 0.6210, 0.6086, 0.5514],
        [0.4109, 0.6119, 0.1966, 0.4355, 0.1589],
        [0.9431, 0.1961, 0.6993, 0.6055, 0.6270],
        [0.4433, 0.8751, 0.1599, 0.9072, 0.5707],
        [0.2688, 0.6926, 0.0670, 0.0393, 0.2087],
        [0.6937, 0.4235, 0.0562, 0.6550, 0.6888]])
torch.Size([10, 5])


### Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 5)

In [3]:
# Create another random tensor with shape (1, 5)
Y = torch.rand(size=(1, 5))

# Transpose the second tensor
Y_transposed = Y.t()

# Perform matrix multiplication
X = torch.matmul(Z, Y_transposed)

# Print the result and its shape
print(X)
print(X.shape)

tensor([[1.5187],
        [1.7300],
        [1.5607],
        [1.7808],
        [1.3555],
        [1.1931],
        [2.1717],
        [2.0606],
        [0.7712],
        [1.8628]])
torch.Size([10, 1])


### Set the random seed

In [6]:
# Set random seed for reproducibility on CPU
torch.manual_seed(0)

# Check if GPU is available and set random seed for reproducibility on GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(0)

# Create random tensor with shape (10, 5)
Z = torch.rand(size=(10, 5))

# Print the random tensor and its shape
print(X)
print(X.shape)

# Create another random tensor with shape (1, 5)
Y = torch.rand(size=(1, 5))


# Perform matrix multiplication
X = torch.matmul(Z, Y_transposed)

# Print the result and its shape
X, X.shape

tensor([[1.1458],
        [2.0642],
        [0.8468],
        [1.4931],
        [2.2232],
        [1.3489],
        [1.1130],
        [1.8159],
        [0.9453],
        [1.6060]])
torch.Size([10, 1])


(tensor([[1.1458],
         [2.0642],
         [0.8468],
         [1.4931],
         [2.2232],
         [1.3489],
         [1.1130],
         [1.8159],
         [0.9453],
         [1.6060]]),
 torch.Size([10, 1]))

### Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [7]:
# Set random seed on the GPU to a different value
torch.cuda.manual_seed(5678)

### Create two random tensors of shape, and send them both to the GPU (you'll need access to a GPU for this)

In [9]:
# Set random seed on the GPU to a different value
torch.cuda.manual_seed(5678)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU with the new seed and different size
tensor_A = torch.rand(size=(3, 4)).to(device)
tensor_B = torch.rand(size=(3, 4)).to(device)
tensor_A, tensor_B

Device: cpu


(tensor([[0.1872, 0.0340, 0.9442, 0.8802],
         [0.0012, 0.5936, 0.4158, 0.4177],
         [0.2711, 0.6923, 0.2038, 0.6833]]),
 tensor([[0.7529, 0.8579, 0.6870, 0.0051],
         [0.1757, 0.7497, 0.6047, 0.1100],
         [0.2121, 0.9704, 0.8369, 0.2820]]))

### Perform a matrix multiplication

In [10]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.8233, 0.7261, 1.1112],
         [0.7979, 0.7425, 1.0420],
         [0.9416, 0.7650, 1.0926]]),
 torch.Size([3, 3]))

### Find the maximum and minimum values

In [11]:
# Find the maximum and minimum values of tensor_C
max_value = torch.max(tensor_C)
min_value = torch.min(tensor_C)

max_value, min_value


(tensor(1.1112), tensor(0.7261))

### Find the maximum and minimum index values

In [12]:
# Find the indices of the maximum and minimum values of tensor_C
max_index = torch.argmax(tensor_C)
min_index = torch.argmin(tensor_C)

max_index, min_index


(tensor(2), tensor(1))

### Make a random tensor, and then create a new tensor with all the 1 dimensions removed to be left. Set the seed and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [14]:
# Set seed to a different value
torch.manual_seed(42)

# Create a random tensor with a different size
tensor_F = torch.rand(size=(1, 1, 1, 8))

# Remove single dimensions
tensor_G = tensor_F.squeeze()

# Print out tensors
print(tensor_F, tensor_F.shape)
print(tensor_G, tensor_G.shape)


tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936]]]]) torch.Size([1, 1, 1, 8])
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936]) torch.Size([8])
